id: IA44E419F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T21:59:32+00:00'
last_modified: '2022-06-15T17:47:41.762688+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC308
  title: 'ཨེ་ཝཾ་བཀའ་འབུམ་ཁ་སྐོང་། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    CE6D:
      image_group_id: I4PD3945
      title: Volume 1 of e waM bka' 'bum kha skong /
      total_pages: 446
      order: 1
      base_file: CE6D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
